### ISSUE TITLE
Nominate channingduan as maintainer

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger/fabric-admin-sdk#70]
as title, nominate @channingduan as maintainer for this project.

duan helps with init features of golang code.

ref to https://github.com/hyperledger/fabric-admin-sdk/pulls?q=is%3Apr+is%3Aclosed+author%3Achanningduan

**Comment by denyeart** [comment]
@SamYuan1990  We typically nominate by updating maintainers file in a PR - https://github.com/hyperledger/fabric-admin-sdk/blob/main/MAINTAINERS.md

And then if a majority of maintainers approve (nominator and one other in this case) then merge the PR and let me know so that I can update fabric-admin-sdk-maintainers team.
